version: 3

tasks:
  clean:
    desc: Clean
    cmds:
      - rm -rf dist

  build:
    desc: Build
    cmds:
      - go mod download
      - go mod tidy
      - go build ./...

  test:
    desc: Test
    cmds:
      - go mod download
      - go mod tidy
      - go test -v ./...

  dependencyUpdates:
    desc: Show dependency updates
    cmds:
      - go mod download
      - go mod tidy
      - go list -u -m -json all | go-mod-outdated -update -direct
